### ISSUE TITLE
Customizing body of widget

### ISSUE THREAD

**Issue by TiaanvdRiel** [fiizzy/Feature-Notifier#2]
Is there any way to customize the body of the notification? For example, add an image of the new feature?

**Comment by fiizzy** [comment]
Heyy @TiaanvdRiel , 
Yes, there is a way to add images of the new feature to the FeatureNotifier widget you are using. For now, only the `FeatureAlertNotifier` and `FeatureBottomModalSheetNotifier` are supported. To use them, simply pass the `image` property of type `Widget` through their constructor. 

If that works or if you happen to still run into any troubles, let me know so we can get that fixed!
Happy coding!

**Comment by coldfingersnz** [comment]
Hi I'm pretty new to Flutter so not sure how you would do that.....do you have an example. I am keen to use this for a What's New pop up displaying some rows of icons and text

**Comment by fiizzy** [comment]
> Hi I'm pretty new to Flutter so not sure how you would do that.....do you have an example. I am keen to use this for a What's New pop-up displaying some rows of icons and text

@coldfingersnz You can easily use `FeatureBottomModalSheetNotifier()` or `FeatureAlertNotifier()` for this purpose. Use the `image` property to pass in whatever widget you want into the Notifier. For example

```dart 
FeatureBottomModalSheetNotifier(
image: Row( #list of icons));

```

Let me know if you run into any more issues!

**Comment by coldfingersnz** [comment]
Fantastic, thanks for the help. This is my implementation......

```dart
ElevatedButton(
                      style: kGreenButtonSettings,
                      onPressed: () {
                        FeatureNotifier.persist(featureKey: 3);
                        FeatureBottomModalSheetNotifier.notify(
                          context,
                          title: "What's New  with Awesome App",
                          description:
                              "Checkout the new features that we just released.",
                          onClose: () {},
                          featureKey: 3,
                          hasButton: true,
                          image: const Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Row(
                              children: [
                                Icon(Icons.ac_unit_outlined),
                                Text('This is a feature'),
                              ],
                            ),
                          ),
                          onTapButton: () {
                            print('Show Features Screen');
                          },
                        );
                      },

```

**Comment by fiizzy** [comment]
Great @coldfingersnz !
Seems like everything works as expected right? If you run into any more trouble, let me know!
Cheers, and happy coding! ❤️

**Comment by fiizzy** [comment]
Hi @coldfingersnz and @TiaanvdRiel !
In the [latest version of FeatureNotifier](https://pub.dev/packages/feature_notifier), I have added a `body` parameter to the `FeatureAlertNotifier()` and `FeatureBottomModalSheetNotifier()` that now allows you to add desired widget to the notifier!

If you have no further questions, I'll just go ahead and close this issue. 🚀
